### ISSUE TITLE
您好，我用这个主题生成页面时遇到错误，可以帮忙看看吗？

### ISSUE THREAD

**Issue by willenigma** [unnamed42/hexo-theme-kunkka#2]
我在运行hexo g命令之后提示了下面的错误信息，可以帮忙看看吗？

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'repo' of undefined
    at Hexo.<anonymous> (E:\TestBlog\themes\kunkka\scripts\generator.js:35:41)
    at Hexo.tryCatcher (E:\TestBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\TestBlog\node_modules\bluebird\js\release\method.js:15:34)
    at E:\TestBlog\node_modules\hexo\lib\hexo\index.js:340:24
    at tryCatcher (E:\TestBlog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\TestBlog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\TestBlog\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (E:\TestBlog\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (E:\TestBlog\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\TestBlog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\TestBlog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\TestBlog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

```

**Comment by unnamed42** [comment]
未定义`repo`……你看看你博客目录下的`_config.yml`（不是我主题下面那个），有没有根据
 https://github.com/hexojs/hexo-deployer-git 配置好？这个变量应该是发布到github上的配置变量

**Comment by unnamed42** [comment]
啊……仔细看了一下，是我的问题，等我改一下
如果方便的话能不能提供一下你的主题下的`_config.yml`呢？

**Comment by willenigma** [comment]
@unnamed42 我的_config.yml就是你主题里边默认的，自己没有修改

**Comment by unnamed42** [comment]
尝试修复了一下，看看修复好了没有

**Comment by willenigma** [comment]
你那里可以了吗，我这里还是不行
```
Unhandled rejection TypeError: E:\TestBlog\themes\kunkka\layout\search.ejs:14
    12| <script src="/js/search.js" type="text/javascript"></script>
    13| <script type="text/javascript">
 >> 14| $(function(){searchFunc('<%- url_for(config.search.path) %>',getParameterByName('keywords'),'search-result')});
    15| </script>
    16|

Cannot read property 'path' of undefined
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:497)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:584)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (E:\TestBlog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (E:\TestBlog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\TestBlog\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (E:\TestBlog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\TestBlog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\TestBlog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:431:10)
    at resume_ (_stream_readable.js:811:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Unhandled rejection TypeError: E:\TestBlog\themes\kunkka\layout\layout.ejs:5
    3|         <!-- Main Content -->
    4|         <%- body || page.content %>
 >> 5|         <%- partial('_partial/sidebar',{cache: !config.relative_link}) %>
    6|     </div>
    7| </div>
    8|

E:\TestBlog\themes\kunkka\layout\_partial\sidebar.ejs:3
    1| <% if(theme.sidebar) { %>
    2| <div id="sidebar">
 >> 3| <%- partial('_widget/recent_comments') %>
    4| <% if (site.posts.length){ %>
    5|     <div class="widget recent-posts"></div>
    6| <% } %>

E:\TestBlog\themes\kunkka\layout\_widget\recent_comments.ejs:1
 >> 1| <% if(theme.duoshuo.shortname || theme.disqus_api_key || theme.github_comment.repo) { %>
    2| <div class="widget widget-comments">
    3|     <h3 class="widget-title"><%= __('recent_comments') %></h3>
    4|     <% if(theme.duoshuo.shortname) { %>

Cannot read property 'shortname' of undefined
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:49)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:743)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:110)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:501)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:190)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:281)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (E:\TestBlog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (E:\TestBlog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\TestBlog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (E:\TestBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\TestBlog\node_modules\bluebird\js\release\promise.js:512:31)
Unhandled rejection TypeError: E:\TestBlog\themes\kunkka\layout\layout.ejs:5
    3|         <!-- Main Content -->
    4|         <%- body || page.content %>
 >> 5|         <%- partial('_partial/sidebar',{cache: !config.relative_link}) %>
    6|     </div>
    7| </div>
    8|

E:\TestBlog\themes\kunkka\layout\_partial\sidebar.ejs:3
    1| <% if(theme.sidebar) { %>
    2| <div id="sidebar">
 >> 3| <%- partial('_widget/recent_comments') %>
    4| <% if (site.posts.length){ %>
    5|     <div class="widget recent-posts"></div>
    6| <% } %>

E:\TestBlog\themes\kunkka\layout\_widget\recent_comments.ejs:1
 >> 1| <% if(theme.duoshuo.shortname || theme.disqus_api_key || theme.github_comment.repo) { %>
    2| <div class="widget widget-comments">
    3|     <h3 class="widget-title"><%= __('recent_comments') %></h3>
    4|     <% if(theme.duoshuo.shortname) { %>

Cannot read property 'shortname' of undefined
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:49)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:743)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:110)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:501)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:190)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:281)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (E:\TestBlog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (E:\TestBlog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\TestBlog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (E:\TestBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\TestBlog\node_modules\bluebird\js\release\promise.js:512:31)
Unhandled rejection TypeError: E:\TestBlog\themes\kunkka\layout\layout.ejs:5
    3|         <!-- Main Content -->
    4|         <%- body || page.content %>
 >> 5|         <%- partial('_partial/sidebar',{cache: !config.relative_link}) %>
    6|     </div>
    7| </div>
    8|

E:\TestBlog\themes\kunkka\layout\_partial\sidebar.ejs:3
    1| <% if(theme.sidebar) { %>
    2| <div id="sidebar">
 >> 3| <%- partial('_widget/recent_comments') %>
    4| <% if (site.posts.length){ %>
    5|     <div class="widget recent-posts"></div>
    6| <% } %>

E:\TestBlog\themes\kunkka\layout\_widget\recent_comments.ejs:1
 >> 1| <% if(theme.duoshuo.shortname || theme.disqus_api_key || theme.github_comment.repo) { %>
    2| <div class="widget widget-comments">
    3|     <h3 class="widget-title"><%= __('recent_comments') %></h3>
    4|     <% if(theme.duoshuo.shortname) { %>

Cannot read property 'shortname' of undefined
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:49)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:743)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:110)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:501)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:190)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:281)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (E:\TestBlog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (E:\TestBlog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\TestBlog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (E:\TestBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\TestBlog\node_modules\bluebird\js\release\promise.js:512:31)
Unhandled rejection TypeError: E:\TestBlog\themes\kunkka\layout\layout.ejs:5
    3|         <!-- Main Content -->
    4|         <%- body || page.content %>
 >> 5|         <%- partial('_partial/sidebar',{cache: !config.relative_link}) %>
    6|     </div>
    7| </div>
    8|

E:\TestBlog\themes\kunkka\layout\_partial\sidebar.ejs:3
    1| <% if(theme.sidebar) { %>
    2| <div id="sidebar">
 >> 3| <%- partial('_widget/recent_comments') %>
    4| <% if (site.posts.length){ %>
    5|     <div class="widget recent-posts"></div>
    6| <% } %>

E:\TestBlog\themes\kunkka\layout\_widget\recent_comments.ejs:1
 >> 1| <% if(theme.duoshuo.shortname || theme.disqus_api_key || theme.github_comment.repo) { %>
    2| <div class="widget widget-comments">
    3|     <h3 class="widget-title"><%= __('recent_comments') %></h3>
    4|     <% if(theme.duoshuo.shortname) { %>

Cannot read property 'shortname' of undefined
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:49)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:743)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:110)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:501)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\TestBlog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\TestBlog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\TestBlog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:190)
    at eval (eval at exports.compile (E:\TestBlog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:281)
    at E:\TestBlog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (E:\TestBlog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (E:\TestBlog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\TestBlog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (E:\TestBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\TestBlog\node_modules\bluebird\js\release\promise.js:512:31)
```

**Comment by unnamed42** [comment]
第一个问题`Cannot read property 'path' of undefined`大概是因为你没有安装或者配置好[hexo-generator-search](https://github.com/PaicHyperionDev/hexo-generator-search)，现在改了之后应该没有装也没有问题，不过还是推荐装一个
第二个问题是因为我没有删除干净多说，已经改了，你再试试
